name: Main Workflow

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch: ~

permissions:
  contents: read
  id-token: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # Check out the repository
      - name: Check Out Code
        uses: actions/checkout@v4

      - &restore-rust
        name: Restore Rust cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup
            target/
          key: ${{ runner.os }}-rust

      # Set up Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

       # Download and unpack Neovim release, placing it in PATH
      - name: Install Neovim
        shell: powershell
        run: |
          $url = "https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-win64.zip"
          $zipPath = "$env:RUNNER_TEMP\nvim-win64.zip"
          $extractPath = "$env:RUNNER_TEMP\"
          Invoke-WebRequest -Uri $url -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractPath
          Write-Output "$extractPath\nvim-win64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      # Build the Rust package
      - name: Build
        run: cargo build --release
        env:
          # Statically link CRT
          RUSTFLAGS: '-C target-feature=+crt-static'

      # Run tests
      - name: Test
        run: cargo test --release

      - name: Hash Rust artifacts
        shell: powershell
        run: |
          $content = Get-ChildItem -Path @("$env:USERPROFILE\.cargo\.crates.toml", "$env:USERPROFILE\.cargo\.crates2.json", "$env:USERPROFILE\.cargo\bin", "$env:USERPROFILE\.cargo\registry\index", "$env:USERPROFILE\.cargo\registry\cache", "$env:USERPROFILE\.cargo\git\db", "$env:RUSTUP_DIR", "target") -File -Recurse -ErrorAction SilentlyContinue | ForEach-Object { 
              $hash = (Get-FileHash -Algorithm MD5 -Path $_.FullName).Hash.ToLower()
              "$hash  $($_.FullName)"
          }
          $writer = [System.IO.StreamWriter]::new('rust-hash', $false, [System.Text.Encoding]::UTF8)
          $writer.Write(($content -join "`n"))
          $writer.Close()
          $writer.Dispose()
          $envHash = (Get-FileHash -Algorithm MD5 -Path rust-hash).Hash.ToLower()
          "RUST_HASH=$envHash" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - &save-rust
        name: Save Rust cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup
            target/
          key: ${{ runner.os }}-rust-${{ env.RUST_HASH }}

      # Upload the executable as an artifact
      - name: Upload Artifact
        if: &is-release-ref startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: clipipe.exe
          path: target/release/clipipe.exe
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: musl-tools sway xwayland
          version: 1.0

      - *restore-rust

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install Neovim
        run: |
          set -x
          url="https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux-x86_64.tar.gz"
          tarpath="$RUNNER_TEMP/nvim-linux-x86_64.tar.gz"
          extractpath="$RUNNER_TEMP/"
          curl --no-progress-meter -f -L -o "$tarpath" "$url"
          tar -C "$extractpath" -x -v -f "$tarpath"
          echo "$extractpath/nvim-linux-x86_64/bin" >> "$GITHUB_PATH"

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Test
        run: |
          set -x
          WLR_LIBINPUT_NO_DEVICES=1
          WLR_BACKENDS=headless
          WAYLAND_DISPLAY=wayland-1
          DISPLAY=:1
          export WLR_LIBINPUT_NO_DEVICES WLR_BACKENDS WAYLAND_DISPLAY DISPLAY
          sway --unsupported-gpu -c /dev/null -d >sway.log 2>&1 &
          pids=$!
          sleep 2
          Xwayland "$DISPLAY" >xwayland.log 2>&1 &
          pids="$pids $!"
          sleep 2
          cargo test --release --target x86_64-unknown-linux-musl
          rc=$?
          kill $pids
          wait
          exit $rc

      - name: Hash Rust artifacts
        run: |
          find ~/.cargo/.crates.toml ~/.cargo/.crates2.json ~/.cargo/bin/ ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/ ~/.rustup target -type f -print0 | xargs -0 md5sum > rust-hash
          echo RUST_HASH=`md5sum rust-hash | cut -d' ' -f 1` >> "$GITHUB_ENV"

      - *save-rust

      - name: Rename, Strip Binary
        if: *is-release-ref
        run: |
          cp target/x86_64-unknown-linux-musl/release/clipipe clipipe-linux-x86_64
          strip clipipe-linux-x86_64

      - name: Upload Artifact
        if: *is-release-ref
        uses: actions/upload-artifact@v4
        with:
          name: clipipe-linux-x86_64
          path: clipipe-linux-x86_64
          if-no-files-found: error

  draft-release:
    if: *is-release-ref
    environment: Publish
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      # Download the built executables
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts/
          merge-multiple: true

      # Create a draft release
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    if: *is-release-ref
    environment: Publish
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Authenticate to crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish to crates.io
        run: cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
